on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Creating release

env:
  # CIBW_TEST_EXTRAS: test
  # CIBW_TEST_COMMAND: "pytest {project}/tests"
  CIBW_TEST_SKIP: "*_arm64 *_universal2:arm64"
  CIBW_ARCHS_MACOS: "x86_64 universal2"

jobs:
  build_wheels:
    name: "[${{ strategy.job-index }}/${{ strategy.job-total }}] py${{ matrix.py }} on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04, windows-2019, macos-14]
        # cp - CPython
        py: ["cp38"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Setting up Python
        with:
          python-version: '3.8'

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_BUILD: "${{ matrix.py }}-*"

      - uses: actions/upload-artifact@v4
        with:
          name: pysimdjson-wheels-${{ matrix.os }}-${{ matrix.py }}
          path: ./wheelhouse/*.whl

  upload_all:
    needs: [build_wheels]
    name: Creating Github release.
    runs-on: ubuntu-latest
    steps:
      - name: Fetch all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release with Notes
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.whl'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
